# Generated by Django 6.0.1 on 2026-10-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_topic_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='entry_uploads/'),
        ),
    ]
