# Generated by Django 6.0.1 on 2026-10-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_entry_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uploaded_file',
        ),
    ]
